name: flutter_starter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:

  http:
  
  table_calendar:

  flutter_rating_bar:
  intl:

  firebase_core:
  firebase_analytics: 
  cloud_firestore:

  firebase_auth: 
  # google_sign_in:
  # apple_sign_in:

  provider: 
  shared_preferences:

  barcode_widget: ^2.0.1

  dio: 
  xml:
  html_unescape: 

  flutter_platform_widgets:
  flutter_sheet_localization: 
  simple_gravatar:

  percent_indicator: ^3.4.0
  
  webview_flutter: ^2.3.0

  flutter_svg: ^0.23.0+1
  url_launcher:
  url_launcher_web: 
  image_picker:
  flutter_email_sender:
  curved_navigation_bar:
  # flutter_auth_buttons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_sheet_localization_generator:
  build_runner: ^1.3.1
  flutter_native_splash:
  flutter_launcher_icons: "^0.9.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/images/defaultDark.png
    - assets/SSB_Logo.png

flutter_icons:
  # To run do: flutter pub run flutter_launcher_icons:main
  image_path: "assets/SSB_Logo.png" 
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  color: "#000000"
  image: assets/SSB_Logo.png

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web 
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true